"""auto migration 20251129_130434

Revision ID: 46aa3b14201d
Revises: 0b6b03b8d40c
Create Date: 2025-11-29 13:04:36.288076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46aa3b14201d'
down_revision: Union[str, None] = '0b6b03b8d40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

