"""auto migration 20251204_063254

Revision ID: 49dae125c2d8
Revises: a3f44bd7d791
Create Date: 2025-12-04 06:32:56.693353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49dae125c2d8'
down_revision: Union[str, None] = 'a3f44bd7d791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

