"""auto migration 20251109_133209

Revision ID: 8c64a4102bae
Revises: 7bb6cf7c0f3d
Create Date: 2025-11-09 13:32:13.818115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c64a4102bae'
down_revision: Union[str, None] = '7bb6cf7c0f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

